.TH AMO 1 "March 2025" "amo 1.0" "Amo Text Editor Manual"

.SH NAME
amo \- lightweight text editor

.SH SYNOPSIS
.B amo
[\fIFILE\fR] [\fIOPTIONS\fR]

.SH DESCRIPTION
amo is a minimal and fast text editor for the command line.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.

.TP
.B \-v, \-\-version
Show version information.

.TP
.B filename
Open the specified file for editing.

.SH EXAMPLES
To open a file:
.B amo myfile.txt

.SH AUTHOR
Written by Sali.
GitHub: Sali-Max
